services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: dependencies
    ports:
      - ${PORT}:8000
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: yarn start:dev
    environment:
      - DB_HOST=postgres

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  postgres:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@saude-bi.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres
