version: '3.9'

volumes:
  geoserver-data:
  geo-db-data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: dependencies
    ports:
      - ${PORT}:8000
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: yarn start:dev
    environment:
      - DB_HOST=postgres

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  postgres:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@saude-bi.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres

  geoserver-db:
    image: kartoza/postgis:16-3.4
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${POSTGRES_GEO_DB}
      - POSTGRES_USER=${POSTGRES_GEO_USER}
      - POSTGRES_PASS=${POSTGRES_GEO_PASS}
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_GEO_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_GEO_USER} -d ${POSTGRES_GEO_DB}"

  geoserver:
    image: kartoza/geoserver:2.24.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_PASSWORD}
    depends_on:
      geoserver-db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u ${GEOSERVER_ADMIN_USER}:'${GEOSERVER_ADMIN_PASSWORD}' http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3
