- name: Playbook Saude-BI Back
  hosts: all
  tasks:
  - name: Getting Docker Repo
    apt_repository:
      name: "Docker"
      baseurl: "https://download.docker.com/linux/ubuntu/dists/jammy/stable"
      gpscheck: "no"
  - name: Installing Docker
    command: "apt install docker-ce --nobest -y"
  - name: Starting Docker
    service:
      name: "docker"
      state: started
      enabled: yes
  - name: "isntall python package"
    package:
      name: "python36"
      state: present
  - name: "installing docker as it uses python"
    command: "pip3 install docker"
  
  - name: Create Docker volumes
      docker_volume:
        name: "volumes"
        state: present
      loop:
        - geoserver-data
        - geo-db-data

    - name: Build and run API container
      docker_container:
        name: api
        image: your_api_image:tag
        build:
          context: .
          dockerfile: Dockerfile-dev
          target: dependencies
        ports:
          - "{{ PORT }}:8000"
        volumes:
          - .:/usr/src/app
        depends_on:
          - postgres
        command: yarn start:dev
        environment:
          - DB_HOST=postgres

    - name: Run Redis container
      docker_container:
        name: redis
        image: redis
        restart_policy: always
        ports:
          - "6379:6379"

    - name: Run Redis Commander container
      docker_container:
        name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
          - "8081:8081"
        environment:
          - REDIS_HOSTS=local:redis:6379
        depends_on:
          - redis

    - name: Run Postgres container
      docker_container:
        name: postgres
        image: postgres
        ports:
          - "{{ DB_PORT }}:5432"
        environment:
          POSTGRES_USER: "{{ DB_USERNAME }}"
          POSTGRES_PASSWORD: "{{ DB_PASSWORD }}"
          POSTGRES_DB: "{{ DB_DATABASE }}"
