name: Continuous Integration
env:
  AWS_REGION: ${{ vars.AWS_REGION }} # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }} # set this to your Amazon ECR repository name

on: 
  push:
    branches: ['master']
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  terraform-deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secreats.AWS_ROLE }}
          aws-region: eu-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.5"

      - name: Init Terraform
        id: terraform-init
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -no-color

      - name: Terraform Plan
        id: terraform-plan
        run: terraform apply -no-color
